---
- file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- openssh_keypair:
   path: "{{ ansible_env.HOME }}/.ssh/helper_rsa"
   size: 4096
   comment: "{{ ansible_env.USER }}@helper"
   state: present

- name: Store the ssh public key to a fact
  shell: cat {{ ansible_env.HOME }}/.ssh/helper_rsa.pub
  register: public_key

- set_fact:
    sshkey: "{{ public_key.stdout }}"vimi 
